#!/bin/bash

set -e

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "$SCRIPT_DIR/lib/helpers.sh"
DOTFILES_DIR="$HOME/.local/share/dotfiles"

# Set initial theme
log_info "Setting up initial theme (everforest)..."
mkdir -p "$DOTFILES_DIR/current"
ln -snf "$DOTFILES_DIR/themes/matte-black" "$DOTFILES_DIR/current/theme"
ln -snf "$DOTFILES_DIR/current/theme/backgrounds/black-hole.jpg" "$DOTFILES_DIR/current/background"

mkdir -p "$HOME/.config/nvim/lua/plugins"
mkdir -p "$HOME/.config/btop/themes"
mkdir -p "$HOME/.config/mako"

ln -snf "$DOTFILES_DIR/current/theme/neovim.lua" "$HOME/.config/nvim/lua/plugins/theme.lua"
ln -snf "$DOTFILES_DIR/current/theme/btop.theme" "$HOME/.config/btop/themes/current.theme"
ln -snf "$DOTFILES_DIR/current/theme/mako.ini" "$HOME/.config/mako/config"

mkdir -p "$HOME/.config/fastfetch"
ln -snf "$DOTFILES_DIR/config/fastfetch/configs/config-default.jsonc" "$HOME/.config/fastfetch/config.jsonc"

log_info "Setting up wallpapers symlink..."
mkdir -p "$HOME/Pictures"
if [ -L "$HOME/Pictures/Wallpapers" ] || [ -d "$HOME/Pictures/Wallpapers" ]; then
  mv "$HOME/Pictures/Wallpapers" "$HOME/Pictures/Wallpapers-backup"
fi
ln -sf "$DOTFILES_DIR/backgrounds" "$HOME/Pictures/Wallpapers"
log_detail "Wallpapers symlinked to ~/Pictures/Wallpapers"

gsettings set org.gnome.desktop.interface icon-theme "Yaru-sage"
gsettings set org.gnome.desktop.interface font-name 'CaskaydiaMono Nerd Font Mono 11'
gsettings set org.gnome.desktop.interface monospace-font-name 'CaskaydiaMono Nerd Font Mono 11'

log_success "Initial theme set (everforest)"
